server:
  port: 8095

spring:
  cloud:
    gateway:
      routes:
      - id: josegalvez-pizzeria
        uri: http://localhost:8082
        predicates:
        - Path=/api/pizzeria/**
  application:
    name: josegalvez-apiserver
